import type { Metadata } from "next"
import "./globals.css"
import { AppRoot } from "@telegram-apps/telegram-ui"
import { TabbarNavbar } from "@/features/main/container/tabbar"
import { Top } from "@/features/top/container/top"
import localFont from "next/font/local"
import type React from "react"

const myFont = localFont({
    src: [
        {
            path: "./fonts/SF-Pro-Display-Medium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/SF-Pro-Display-Semibold.otf",
            weight: "600",
            style: "normal",
        },
        {
            path: "./fonts/SF-Pro-Display-Bold.otf",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/SF-Pro-Display-Heavy.otf",
            weight: "800",
            style: "normal",
        },
    ],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
        <body className={`${myFont.className} w-full antialiased`}>
        <AppRoot className="flex flex-col bg-transparent h-[var(--tg-viewport-stable-height,100vh)]">
            <Top />
            <main className="flex-1 overflow-y-auto scrollbar-hide overflow-x-hidden">
                <div className="min-h-[var(--tg-viewport-stable-height,100vh)]">{children}</div>
            </main>
            <TabbarNavbar />
        </AppRoot>
        </body>
        </html>
    )
}

