import type { Metadata } from "next"
import "./globals.css"
import { AppRoot } from "@telegram-apps/telegram-ui"
import { TabbarNavbar } from "@/features/main/container/tabbar"
import { Top } from "@/features/top/container/top"
import localFont from "next/font/local"
import type React from "react"
import {locales} from "../../../config";
import {unstable_setRequestLocale} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";

export function generateStaticParams() {
    return locales.map((locale) => ({ locale }));
}

type Locale = 'en' | 'ru';

type Params = {
    locale: Locale;
};

const myFont = localFont({
    src: [
        {
            path: "./fonts/SF-Pro-Display-Medium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/SF-Pro-Display-Semibold.otf",
            weight: "600",
            style: "normal",
        },
        {
            path: "./fonts/SF-Pro-Display-Bold.otf",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/SF-Pro-Display-Heavy.otf",
            weight: "800",
            style: "normal",
        },
    ],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function LocaleLayout({
                                               children,
                                               params,
                                           }: {
    children: React.ReactNode;
    params: Params; // Без Promise
}) {

    const { locale } = await params;

    unstable_setRequestLocale(locale);

    let messages: Record<string, string>;
    try {
        messages = (await import(`../../../messages/${locale}.json`)).default;
    } catch (error) {
        console.error("Error loading locale messages:", error);
        messages = {};
    }

    return (

        <html lang="en">
        <body className={`${myFont.className} w-full antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
            <AppRoot className="flex flex-col bg-transparent h-[var(--tg-viewport-stable-height,100vh)]">
                <main className="flex-1 overflow-y-auto scrollbar-hide overflow-x-hidden">
                    <div className="min-h-[var(--tg-viewport-stable-height,100vh)]">{children}</div>
                </main>
            </AppRoot>
        </NextIntlClientProvider>
        </body>
        </html>
    )
}

